### ISSUE TITLE
client-side-force-version setting

### ISSUE THREAD

**Issue by Bluscream** [ViaVersion/ViaFabric#172]
**Is your feature request related to a problem? Please describe.**
Nope. uwu

**Is this related specifically to ViaFabric?**
(Optional)
- [x] It seems to not apply for ViaVersion/ViaBackwards/ViaRewind installed on Bukkit/BungeeCord/Sponge/Velocity servers.

**Describe the solution you'd like**
A new setting block in the viafabric.yml that allows us to permanently set a forced versions for specific servers

```yaml
client-side-force-version:
- 2b2t.org: 1.12.2
- play.tasmantismc.com: >1.18
```

(Ideally this can be set ingame with a textbox on the server entry edit screen)

**Describe alternatives you've considered**
Manual labor

**Which versions is this for?**
all of dem
